[package]
license = ["Apache-2.0"]
keywords = ["Commerce/eCommerce", "Cost/Free", "Vendor/Google"]
org = "ballerinax"
name = "googleapis.mybusiness"
icon = "icon.png"
distribution = "2201.3.1"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.2.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
