[package]
license = ["Apache-2.0"]
keywords = ["Human Resources/HRM", "Cost/Paid"]
org = "ballerinax"
name = "workday.compensation"
icon = "icon.png"
distribution = "2201.3.1"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.2.1"
authors = ["Ballerina"]
