[package]
license = ["Apache-2.0"]
keywords = ["Lifestyle & Entertainment/App Store", "Cost/Paid"]
org = "ballerinax"
name = "apple.appstore"
distribution = "2201.3.1"
repository = "https://github.com/ballerina-platform/ballerinax-openapi-connectors"
version = "1.2.1"
authors = ["Ballerina"]
[build-options]
observabilityIncluded = true
